#coding=utf-8

price=3.8
weight=2.9
g=8
price_sum=price*weight*g
jg=input('请输入西瓜价格')
jgprice=float(jg)
print('西瓜价格是%.2f元/斤'%jgprice)
zl=input('请输入西瓜重量')
zlweight=float(zl)
print('西瓜重量是%.2f斤'%zlweight)
money=jgprice*zlweight
print('您需要支付%.2f元'%money)

'''
#输入西瓜单价
jg=input('请输入西瓜价格')
#要求西瓜重量
zl=input('请输入西瓜重量')
#计算金额
#1>将西瓜单位转化小数
price=float(jg)
#2>将西瓜重量转化为小数
weight=float(zl)
#计算付款金额
money=price*weight
#输出
print('付款金额应为',money)
'''
