
t=open('shi.c','w+')
t.write('早发白帝城\n招辞白帝彩云间，\n千里江陵一日还。\n两岸猿声啼不住，\n轻舟一过万重山。\n')
t.close()

f=open('shi.c','r')
f.readline()
a=f.tell()
print('文件读取的第一个开始：%d '% a)
f.readline()
a=f.tell()
print('文件读取的第二个开始：%d '% a)
f.readline()
a=f.tell()
print('文件读取的第三个开始：%d '% a)
f.readline()
a=f.tell()
print('文件读取的第四个开始：%d '% a)
f.readline()
a=f.tell()
print('文件读取的第五个开始：%d '% a)
f.close()

f=open('shi.c','r')
c=f.seek(5,0)
print('从读取位置开始偏移5个：%d'% c)
